arches:
  - x86_64
  - ppc64le

stages:
- image: registry.access.redhat.com/ubi9/python-312-minimal:1
  packages:
    - cmake
    - rust
    - cargo
    - openblas-devel
    - libstdc++-static
    - ncurses-devel
    - perl
    - git
    - make
    - wget
    - unzip
    - unixODBC-devel
    - lz4-devel
    - libtool
    - libicu 
    - libpq
    - gcc
    - python3.12-devel
    - postgresql-devel
