arches:
  - x86_64
  - ppc64le

stages:
- image: registry.access.redhat.com/ubi9/python-311:1
  packages:
    - ninja-build
    - llvm-devel
    - cmake
    - llvm-toolset
    - rust
    - cargo
    - gcc-toolset-13
    - libuuid-devel
    - openblas-devel
    - libstdc++-static
    - libaio
    - libtool
    - ncurses-devel
    - perl
